### ISSUE TITLE
React-Swiper-堆叠式 卡片式

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/React-learn#32]
swiper.js
```js
import React, { Component } from 'react'
import './xin-swiper.scss'
export default class XinSwiper extends Component {
    constructor(props){
        super(props)
        this.state = {
            list:[
                {
                    name:1
                },
                {
                    name:2
                },
                {
                    name:3
                },
            ],
            current: 1, // 轮播图当前 index
            itemWidth:0, //  图片区域 宽度
            out: 1,  // 堆叠式 外部看到的数量 （左右各相同） 不限制 可以设置 0 或 大于轮播图数量
            offset:90, // 堆叠式 外部偏移量 (产生堆叠效果)
            startTime: 0,
            startX: 0,
            startY: 0,
        }
    }
    componentDidMount(){
        // 获取轮播图片区域宽度
        const width = this.refs.swiperitem.clientWidth
        this.setState({
            itemWidth:width
        })
    }
    // 上一张
    onPrev = (index) => {
        const length = this.state.list.length
        if( index - 1 < 0) {
            this.setState({
                current : length -1
            })
        }else {
            this.setState({
                current : index -1
            })
        }
    }
    // 下一张
    onNext = (index) => {
        const length = this.state.list.length
        if ( index + 1 === length) {
            this.setState({
                current: 0
            })
        }else{
            this.setState({
                current: index + 1
            })
        }
    }
    handelTouchStart = (e) => {
        this.setState({
            startTime:Date.now(),
            startX:e.changedTouches[0].clientX,
            startY:e.changedTouches[0].clientY
        })
    }
    handelTouchend = (e) => {
        const { startX,startY } = this.state
        let endTime = Date.now()
        let endX = e.changedTouches[0].clientX;
        let endY = e.changedTouches[0].clientY;
        if (endTime - this.startTime > 2500) { //正常操作不会大于2.5秒
            return;
        }
        //如果Y轴移动小于10,泽上下滑动
        if (Math.abs(endX - startX) > 10 && Math.abs(endY - startY) < 10) {
            // endX - startX > 0 ? 'right' : 'left'
            let {current} = this.state
            endX - startX > 0 ? this.onPrev(current) : this.onNext(current)
        }
    }

    render() {
        let  {list,current,itemWidth,out,offset} = this.state
        // 水平式   计算轮播区整体位移
        let x = current === 0 ? 0 : - current*itemWidth +'px'
        const translateX = `translateX(${x})`
        return (
            <div className="card-carousels">
                <div className='btn-prev' onClick={ () => this.onPrev(current)}>左按钮</div>
                <div className='btn-next' onClick={ () => this.onNext(current)}>右按钮</div>
                {/*卡片式*/}
                {/*<div className='wrapper'>*/}
                {/*    <div className='inner'>*/}
                {/*        <div ref='swiper' className='swiper' style={{ transform: translateX}}>*/}
                {/*            {*/}
                {/*                list.map( (item,key) =>*/}
                {/*                    (*/}
                {/*                        <div*/}
                {/*                            ref='swiperitem'*/}
                {/*                            className={['swiper-item', key === current ? 'current' : ''].join(" ")} key={key}*/}
                {/*                            onTouchStart={this.handelTouchStart}*/}
                {/*                            onTouchEnd={this.handelTouchend}*/}
                {/*                        >*/}
                {/*                            <div className='pic' >{item.name}</div>*/}
                {/*                        </div>*/}
                {/*                    )*/}
                {/*                )}*/}
                {/*        </div>*/}
                {/*    </div>*/}
                {/*</div>*/}

                <div className='wrapper'>
                    <div className='inner'>
                        <div className='swiper2'>
                            {
                                list.map((item , index ) => {
                                    // 层叠式 计算各张图片 translateX scale  z-index 产生堆叠效果
                                    let transform = 'none'
                                    let zIndex = 0
                                    let opacity = 1
                                    // if(out ? index < current && current - index <= out : index < current){
                                    //     // 左边 堆叠
                                    //     zIndex = index +1
                                    //     transform = `translateX(${(index - current)*offset}px) scale(${1-(current-index)*0.1})`
                                    // }else if(out ?  index > current && index - current <= out : index> current){
                                    //     // 右边 堆叠
                                    //     zIndex = list.length - index
                                    //     transform = `translateX(${(index - current)*offset}px) scale(${1-(index-current)*0.1})`
                                    // }else if (index === current){
                                    //     // 当前图片
                                    //     zIndex = list.length
                                    // }
                                    if(current === 0 && list.length -1 === index ){
                                        transform = `translateX(${0-offset}px) scale(0.9)`
                                        opacity = 0.5
                                    } else if(current === list.length -1 && index === 0 ){
                                        transform = `translateX(${offset}px) scale(0.9)`
                                        opacity = 0.5
                                    } else if(index === current - 1){
                                        // 左边 堆叠
                                        zIndex = index +1
                                        transform = `translateX(${0-offset}px) scale(0.9)`
                                        opacity = 0.5
                                    }else if(index === current + 1){
                                        // 右边 堆叠
                                        zIndex = list.length - index
                                        transform = `translateX(${offset}px) scale(0.9)`
                                        opacity = 0.5
                                    }else if (index === current){
                                        // 当前图片
                                        zIndex = list.length
                                    }
                                    return (
                                        <div
                                            className='swiper-item'
                                            key={index} style={{transform,zIndex,opacity}}
                                            onTouchStart={this.handelTouchStart}
                                            onTouchEnd={this.handelTouchend}
                                        >
                                            {item.name}
                                        </div>
                                    )
                                })
                            }
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}


```
swiper.css
```css
.card-carousels{
  div{
    box-sizing: border-box;
  }
  .wrapper{
    width: 100%;
    margin:30px auto;
    border:1px solid #ccc;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    .btn-prev,.btn-next{
      position: absolute;
      width: 40px;
      height: 40px;
      background: rgba(0,0,0,.3);
      color: white;
      line-height: 40px;
      text-align: center;
      z-index: 9;
      cursor:pointer
    }
    .inner{
      position: relative;
      width: 504px;
      height: 470px;
      background: #FFFFFF;
      border-radius: 10px;
      .swiper{
        position: absolute;
        top:0;
        left: 0;
        height: 100%;
        min-width: 100%;
        display: flex;
        flex-wrap: nowrap;
        transition: all 0.5s;
        .swiper-item{
          padding:0 20px;
          width: 400px;
          transition:all 0.5s;
          transform: scale(0.8);
          &.current{
            transform:scale(1);
          }
          .pic{
            border:1px solid pink;
            border-radius: 20px;
            height: 100%;
            line-height: 200px;
            font-size: 50px;
            background:#ccc;
          }
        }
      }
      .swiper2, .swiper2 .swiper-item{
        position: absolute;
        left:0;
        top:0;
        width:100%;
        height: 100%;
        font-size: 50px;
        text-align: center;
        line-height: 150px;
      }
      .swiper2 .swiper-item{
        transition: transform .5s;
        border:2px solid #ccc;
        color:black;
        border-radius: 20px;
        background: white;
      }
    }
  }
}

```
