### ISSUE TITLE
React-类组件+Hook实现内容过多 （展开收起功能）

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/React-learn#6]
> 思路：父元素 overflow:hidden 子元素中渲染内容  
> 展开时：给父元素最大高度：
> 收起时：取消父元素最大高度
> 判断：最大高度 是否大于 内容实际撑起的高度  大于  无展开和收起

```js
/**
 * @file fold
 * @author v_kuiyufeng
 * @owner v_kuiyufeng:2020-06-19
 */
import * as React from 'react'
// import * as PropTypes from 'prop-types'
import { default as c } from 'classnames'
import { CompBaseProps } from '@befe/brick-mobile-utils'
import { useState, useEffect } from 'react'


export interface FoldProps extends CompBaseProps {
    /**
     * 自定义class
     */
    className?: string
    /**
     * 最大高度设置
     */
    maxHeight: number;
    /**
     * 自定义文本默认：展开
     */
    unPackText?: string
    /**
     * 自定义文本默认：收起
     */
    packText?: string
    /**
     * slot
     */
    children: any
}

/**
 * Fold
 * @description one-ui component Fold
 */
export const Fold = (props: FoldProps) => {
    const prefixCls = 'brick-mobile-fold'
    const {
        maxHeight,
        unPackText = '展开',
        packText = '收起',
        children,
        className
    } = props
    const contentRef = React.createRef<HTMLDivElement>()
    const contentWrapperRef = React.createRef<HTMLDivElement>();
    const [contentHeight, setContentHeight] = useState(0);
    const [contentWrapperHeight, setContentWrapperHeight] = useState(0);
    const [showAll, setShowAll] = useState(false);
    useEffect(() => {
        freshHeight();
    })
    const freshHeight = () => {
        const newContentHeignt = contentRef.current.getBoundingClientRect().height;
        const newContentWrapperHeight = contentWrapperRef.current.getBoundingClientRect().height;
        if (newContentHeignt !== contentHeight || newContentWrapperHeight !== contentWrapperHeight) {
            setContentHeight(newContentHeignt)
            setContentWrapperHeight(newContentWrapperHeight)
        }
    }

    const getClassName = () => {
        return c(
            prefixCls,
            className
        )
    }
    const isOverFlow = () => contentHeight > maxHeight;

    const showUnPack = () => {
        return !showAll
            && isOverFlow()
            && contentWrapperHeight < contentHeight;
    }

    const showPack = () => {
        return showAll && contentWrapperHeight > maxHeight;
    }
    
    return (
        <div className={`${getClassName()} comps-ellipsis`}>
            <div
                ref={contentWrapperRef}
                className="comps-content-wrapper"
                style={{ maxHeight: showAll ? undefined : `${maxHeight}px` }}
            >
                <div
                    ref={contentRef}
                    className="comps-content"
                >
                    {children}
                </div>
            </div>
            {
                showUnPack() &&
                <div
                    className="comps-ellipsis-unpack"
                    onClick={() => {
                        setShowAll(true)
                    }}
                >
                    {unPackText}
                </div>
            }
            {
                showPack() &&
                <div
                    onClick={() => {
                        setShowAll(false)
                    }}
                    className="comps-ellipsis-pack"
                >
                    {packText}
                </div>
            }
        </div>
    )
}

```
```scss
@import "~@befe/brick-mobile-style/src/base";

@include exports('mobile-comp-fold') {
    .brick-mobile-fold {
        @include reset();
    }
    .comps-ellipsis {
        position: relative;
        .comps-content-wrapper {
            overflow: hidden;
        }
        .comps-content{
            font-size: 14px;
        }
        .comps-ellipsis-unpack , .comps-ellipsis-pack{
            float: right;
            margin-right: 0px;
            margin-top: 12px;
            color: #409eff;
            font-size: 14px;
            color: #5A90FA;
            letter-spacing: 0;
        }
    }

}

```
