### ISSUE TITLE
React-内容过多，文本缩略问题,文本截断问题

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/React-learn#7]
```css
//单行省略
{
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
//多行换行省略
{
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
```
### 多行省略中间

“我的文件不知道在那里呢
你告诉我在...好吗.pdf”

- 将文本放入div容器中
- 判断是否溢出
- 若不溢出 返回文本
- 若溢出 减少文本（增加...）并重复步骤1

### 文本内容截断

https://www.npmjs.com/package/react-lines-ellipsis

```js
import LinesEllipsis from 'react-lines-ellipsis';

<LinesEllipsis
  text='long long text'
  maxLine='3'
  ellipsis='...'
  trimRight
  basedOn='letters'
/>
```
