### ISSUE TITLE
React-移动端播放语音功能

### ISSUE THREAD

**Issue by PleaseStartYourPerformance** [PleaseStartYourPerformance/React-learn#9]
### index.tsx
```ts
/**
 * @file audio
 * @author v_kuiyufeng
 * @owner v_kuiyufeng:2020-06-28
 */
import React from 'react'
// import * as PropTypes from 'prop-types'
import {CompBaseProps} from '@befe/brick-mobile-utils'

import { Media, Player, controls } from 'react-media-player';
import PlayPause from './components/play-pause';
import SeekBar from './components/seek-bar';
import CurrentTime from './components/current-time';

export interface AudioProps extends CompBaseProps {
    /**
     * 语音url
     */
    audioUrl:string
}

const {Duration} = controls;
/**
 * Audio
 * @description  component Audio
 */
export const Audio = (props: AudioProps) => {
    const prefixCls = 'brick-mobile-audio-';
    const {audioUrl} = props;
    return (
        <Media key={audioUrl}>
            {() => {
                return <div className="brick-mobile-audio">
                    <Player src={audioUrl} className={prefixCls+'media-player'} />
                    <div className={prefixCls + 'media-controls'}>
                        <PlayPause />
                        <SeekBar />
                        <CurrentTime />
                        <span className={prefixCls + 'slanting'}> / </span>
                        <Duration />
                    </div>
                </div>;
            }
            }
        </Media>
    )
}

```
### play-pause.tsx
```ts
import React from 'react';
// import './index.less';
import {withMediaProps} from 'react-media-player';
import playPng from '../imgs/play.png';
import pausePng from '../imgs/pause.png';
interface playPauseProps{
    media:any
}

class PlayPause extends React.PureComponent<playPauseProps> {
    constructor(props:playPauseProps){
        super(props)
    }
    handlePlayPause = () => {
        this.props.media.playPause();
    }
    render() {
        const {media} = this.props;
        return (
            <button
                type="button"
                className="brick-mobile-audio-control-button"
                onClick={this.handlePlayPause}
            >
                {
                    <img
                        className="control-img"
                        src={media.isPlaying ? playPng : pausePng} />
                }
            </button>
        );
    }
}

export default withMediaProps(PlayPause);

```
### seek-bar.tsx
```ts
import React from 'react';
// import './index.less';
import {withMediaProps} from 'react-media-player';
interface SeekBarProps{
    media:any;
}
class SeekBar extends React.PureComponent<SeekBarProps> {
    isPlayingOnMouseDown = false
    onChangeUsed = false

    handleMouseDown = () => {
        this.isPlayingOnMouseDown = this.props.media.isPlaying;
        this.props.media.pause();
    }

    handleMouseUp = ({target: {value}}) => {
        //ie11以下有问题
        !this.onChangeUsed && this.props.media.seekTo(+value);
        this.isPlayingOnMouseDown &&   this.props.media.play();
    }

    handleChange = ({target: {value}}) => {
        this.props.media.seekTo(+value);
        this.onChangeUsed = true;
    }

    render() {
        const {media} = this.props;
        const {duration, currentTime} = media;
        return (
            <input
                type="range"
                step="any"
                max={duration.toFixed(4)}
                value={currentTime}
                onMouseDown={this.handleMouseDown}
                onMouseUp={this.handleMouseUp}
                onChange={this.handleChange}
                className="range"
                style={{
                    backgroundSize: currentTime * 100 / duration + '% 100%',
                }}
            />
        );
    }
}

export default withMediaProps(SeekBar);
```
### current-time.tsx
```ts
import React from 'react';
import {withMediaProps, utils} from 'react-media-player';
const {formatTime} = utils;
interface CurrentTimeProps{
    className:string;
    media:any;
}

class CurrentTime extends React.PureComponent<CurrentTimeProps> {
    render() {
        const {className, media} = this.props;
        console.log(this.props)
        return (
            <time className={className}>
                {formatTime(media.currentTime)}
            </time>
        );
    }
}

export default withMediaProps(CurrentTime);

```

### index.scss
```scss
@import "~@befe/brick-mobile-style/src/base";
@include exports('mobile-comp-audio') {
  .brick-mobile-audio {
    @include reset();
    font-size: 14px;
    &-media-player{
      display: none;
    }
    &-media-controls {
      display: flex;
      align-items: center;
  }
    &-slanting {
        margin: 0 3px;
    }
    &-control-button {
        width: 20px;
        height: 20px;
        border: none;
        background: none;
        outline: none;
        img.control-img {
            width: 10px;
            height: 10px;
            margin-top: -4px;
        }
    }
    input[type=range].range {
      margin: 0 6px;
      outline: none;
      /*清除系统默认样式*/
      -webkit-appearance: none;
      width: 90px;
      /*横条的高度*/
      height: 3px;
      background: -moz-linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
      background: -webkit-linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
      background: -o-linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
      background: -ms-linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
      background: linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
      /*设置左右宽度比例*/
      background-size: 30% 100%;
      &:focus {
          border: none;
      }
  }
  /*firefox去input range 的outline*/
  input[type=range].range::-moz-focus-outer {
      border: 0;
    }
  /*chrome、safari下拖动块的样式*/
  input[type=range].range::-webkit-slider-thumb {
      /*清除系统默认样式*/
      -webkit-appearance: none;
      width: 6px;
      height: 6px;
      background: #fff;
      border-radius: 50%;
      border: 1px solid #54A1FF;
      &:hover {
          width: 10px;
          height: 10px;
      }
  }
  /*firefox下拖动块的样式*/
  input[type=range].range::-moz-range-thumb {
      -webkit-appearance: none;
      width: 6px;
      height: 6px;
      background: #fff;
      border-radius: 50%;
      border: 1px solid #54A1FF;
      &:hover {
          width: 10px;
          height: 10px;
      }
  }
  /*ie下拖动块的样式*/
  input[type=range].range::-ms-thumb {
      -webkit-appearance: none;
      width: 6px;
      height: 6px;
      background: #fff;
      border-radius: 50%;
      border: 1px solid #54A1FF;
      &:hover {
          width: 10px;
          height: 10px;
      }
  }
  input[type=range].range::-moz-range-progress {
      background: linear-gradient(#54A1FF, #54A1FF) no-repeat, #e0e0e0;
  }
  }
}

```
### demo
```
<Audio audioUrl={xxx}/>
```
